# Generated by Django 6.0.2 on 2026-02-12 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelacaoContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uasg', models.IntegerField(help_text='Número inteiro com seis dígitos', validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='UASG')),
                ('nomeUasg', models.CharField(choices=[('UC', 'UC'), ('RF 01', 'RF 01'), ('RF 02', 'RF 02'), ('RF 03', 'RF 03'), ('RF 04', 'RF 04'), ('RF 05', 'RF 05'), ('RF 06', 'RF 06'), ('RF 07', 'RF 07'), ('RF 08', 'RF 08'), ('RF 09', 'RF 09'), ('RF 10', 'RF 10')], max_length=10, verbose_name='Nome UASG')),
                ('numContrato', models.CharField(help_text='Ex: 03/2025', max_length=20, verbose_name='Número do Contrato')),
                ('objetoContrato', models.TextField(help_text='Ex: motoristas, apoio administrativo', verbose_name='Objeto do Contrato')),
                ('inicioVigenciaContrato', models.DateField(verbose_name='Início da Vigência')),
                ('fimVigenciaContrato', models.DateField(verbose_name='Fim da Vigência')),
                ('identificadorContrato', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Identificador do Contrato')),
            ],
            options={
                'verbose_name': 'Relação de Contrato',
                'verbose_name_plural': 'Relações de Contratos',
            },
        ),
    ]
