# Generated by Django 6.0.2 on 2026-02-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacaocontratos',
            name='pi',
            field=models.CharField(choices=[('Custeio', 'Custeio'), ('Investimento', 'Investimento'), ('PIU', 'PIU')], default='Custeio', max_length=20, verbose_name='PI'),
        ),
    ]
