# Generated by Django 6.0.1 on 2026-02-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofi', '0002_relacaocontratos_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacaocontratos',
            name='valorMensalPrevisto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Mensal Previsto'),
        ),
    ]
