# Generated by Django 6.0.1 on 2026-02-13 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofi', '0003_relacaocontratos_valormensalprevisto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacaocontratos',
            name='identificadorContrato',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='Id do Contrato'),
        ),
        migrations.CreateModel(
            name='RelacaoMedicoesRealizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesMedicao', models.CharField(choices=[('JAN', 'JAN'), ('FEV', 'FEV'), ('MAR', 'MAR'), ('ABR', 'ABR'), ('MAI', 'MAI'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AGO', 'AGO'), ('SET', 'SET'), ('OUT', 'OUT'), ('NOV', 'NOV'), ('DEZ', 'DEZ')], max_length=3, verbose_name='Mês da Medição')),
                ('anoMedicao', models.IntegerField(verbose_name='Ano da Medição')),
                ('valorLiquidado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Liquidado')),
                ('identificadorMedicao', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Id da Medição')),
                ('identificadorContrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geofi.relacaocontratos', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Relação de Medição Realizada',
                'verbose_name_plural': 'Relações de Medições Realizadas',
            },
        ),
    ]
